/* eslint-disable @next/next/no-img-element */
import {useRef, useEffect} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { gsap } from 'gsap';

export default function Home() {

  const headerRef = useRef(null)
  const image = useRef(null)
  const heading1 = useRef(null)
  const heading2 = useRef(null)
  const heading = useRef(null)
  const text = useRef(null)

  useEffect(() => {
    gsap.from(headerRef.current, {
      // duration:1,
      autoAlpha:0,
      // ease:'none',
      delay:1
    })

    gsap.from(image.current, {
      duration:1,
      delay:1,
      autoAlpha:0,
      y:-20, 
      // scale:0  
    })
    
    gsap.from(heading1.current, {
      // duration:1.5,
      delay:2,
      // stagger:0.1,
      y:-10,
      x:10,
      autoAlpha:0,
    })
    gsap.from(heading2.current, {
      // duration:1.5,
      delay:2.2,
      // stagger:0.1,
      y:-10,
      x:10,
      autoAlpha:0,
    })
    gsap.from(heading.current, {
      // duration:1.5,
      delay:2.3,
      // stagger:0.1,
      y:-10,
      x:10,
      autoAlpha:0,
    })
   gsap.from(text.current, {
     autoAlpha:0,
     delay:2.5
   })
  }, [])

  return (
    <div ref={headerRef} className="bg-black w-screen h-screen">
      <Head>
        <title>Near you</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center w-screen h-screen">
        <div className="max-h-80 relative">
          <img ref={image} src="/eye.jpg" alt="" className='w-full h-full' />
        </div>
        <div className="flex flex-col mt-24 relative">
          <img ref={heading1}  className="h-7 md:h-14 absolute -top-5 md:-top-10 -right-5 md:-right-10" src="/heading-outline.svg" alt="" />
          <img ref={heading2}  className='h-7 md:h-14 absolute -top-3 md:-top-5 -right-3 md:-right-5' src="/heading-outline.svg" alt="" />
          <img ref={heading}  className='h-7 md:h-14' src="/heading-filled.svg" alt="" />
        </div>
        <h1 ref={text} className='text-white mt-10 text-sm md:text-xl tracking-wider uppercase italic dm-sans'>i always near</h1>
      </div>
    </div>
  )
}
