/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Near you</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
        <div className={styles.imageContainer}>
         <img src="/eye.jpg" className={styles.image} alt="eyes"/>
        </div>
        <div className={styles.heading}>
          <img src="/heading-outline.svg" alt="" id={styles.outline}  />
          <img src="/heading-outline.svg" alt="" id={styles.outline2}  />
          <img src="/heading-filled.svg" alt=""  id={styles.filled}/>
        </div>
        <p className={styles.text}>I always near</p>
      </div>
    </div>
  )
}
